<Ex_Screen>:
    AnchorLayout:
        anchor_x: 'center'
        anchor_y: 'bottom'
        BoxLayout:
            spacing: 15
            orientation: 'horizontal'
            size_hint: [1, .25]
            Button:
                id: calendar
                background_normal: 'i_calendar.png'
                background_down:'i_calendar2.jpg'
                on_press: root.go_to_calendar()
            Button:
                id: exercise
                background_normal: 'i_ex.png'
                background_down:'i_ex2.jpg'
            Button:
                id: train
                background_normal: 'i_train.png'
                background_down:'i_train2.jpg'
                on_press: root.default_view(), root.go_to_train(),
            Button:
                id: statistic
                background_normal: 'i_stat.png'
    AnchorLayout:
        anchor_x: 'center'
        anchor_y: 'top'
        GridLayout:
            cols:2
            size_hint: [.5, .1]
            padding: 0, 0, 0, 0
            TextInput:
                id: search
                text: 'Введите название упражнения'
                on_focus: root.default_fill_search()
            AnchorLayout:
                anchor_x: 'left'
                anchor_y: 'top'
                size_hint: [.2, 1]
                Button:
                    id: find
                    text: 'Найти'
                    on_press: root.find(), root.remove_label_text(), root.add_descr()
    AnchorLayout:
        anchor_x: 'center'
        anchor_y: 'center'
        GridLayout:
            id: central_grid
            rows: 2
            size_hint: [.9, .6]
            ScrollView:
                do_scroll_x: False
                Label:
                    id: l1
                    text_size: self.size
                    size_hint_y: None
                    height: self.texture_size[1] + dp(10)
                    text_size: self.width, None
                    text: ''
            ScrollView:
                do_scroll_x: False
                Label:
                    id: l2
                    text_size: self.size
                    size_hint_y: None
                    height: self.texture_size[1] + dp(10)

                    text_size: self.width, None
                    text: ''

<Train_Screen>:
    AnchorLayout:
        anchor_x: 'center'
        anchor_y: 'bottom'
        BoxLayout:
            spacing: 15
            orientation: 'horizontal'
            size_hint: [1, .15]
            Button:
                id: calendar
                text: 'Cal'
                on_press: root.go_to_calendar()
            Button:
                id: exercise
                text: 'Ex'
                on_press: root.go_to_ex()
            Button:
                id: train
                text: 'Tr'
            Button:
                id: statistic
                text: 'Stat'
    AnchorLayout:
        anchor_x: 'center'
        anchor_y: 'center'
        BoxLayout:
            spacing: 20
            orientation: 'vertical'
            size_hint: [.4, .5]
            Button:
                name: start
                id: start
                text: 'Начать тренировку'
                on_press: root.go_to_train_start()
            Button:
                id: skip
                text: 'Пропустить тренировку'


<Train_Start_Screen>:
    AnchorLayout:
        anchor_x: 'center'
        anchor_y: 'bottom'
        BoxLayout:
            spacing: 15
            orientation: 'horizontal'
            size_hint: [1, .15]
            Button:
                id: calendar
                text: 'Cal'
                on_press: root.go_to_calendar()
            Button:
                id: exercise
                text: 'Ex'
                on_press: root.go_to_ex()
            Button:
                id: train
                text: 'Tr'
            Button:
                id: statistic
                text: 'Stat'
    AnchorLayout:
        anchor_x: 'center'
        anchor_y: 'center'
        BoxLayout:
            id: active_train_mode
            spacing: 20
            orientation: 'vertical'
            size_hint: [.4, .5]
            Label:
                id: time_label
                text: '00:00'
            Label:
                id: train_label
            GridLayout:
                id: grid_ex_number
                cols: 3
            Button:
                text: 'start'
                on_press: root.call_next_ex(), root.current_train(), root.create_labels(), root.current_number()
            Label:
                id: ex_info_label
<Train_Finish_Screen>:
    AnchorLayout:
        anchor_x: 'center'
        anchor_y: 'bottom'
        BoxLayout:
            spacing: 15
            orientation: 'horizontal'
            size_hint: [1, .15]
            Button:
                id: calendar
                text: 'Cal'
                on_press: root.go_to_calendar()
            Button:
                id: exercise
                text: 'Ex'
                on_press: root.go_to_ex()
            Button:
                id: train
                text: 'Tr'
            Button:
                id: statistic
                text: 'Stat'

<Calendar_Screen>:
    AnchorLayout:
        anchor_x: 'center'
        anchor_y: 'bottom'
        BoxLayout:
            spacing: 15
            orientation: 'horizontal'
            size_hint: [1, .15]
            Button:
                id: calendar
                text: 'Cal'

            Button:
                id: exercise
                text: 'Ex'
                on_press: root.go_to_ex()
            Button:
                id: train
                text: 'Tr'
                on_press: root.go_to_train()
            Button:
                id: statistic
                text: 'Stat'